name: first workflow
on:
  push:
    branches:
      - "main"
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "Hello"
      - name: print goodbye
        run: |
             echo "bye"
             echo "second bye"
